% fft r4 and 2r2

fft_prm = struct( ...
   'size',    32,     ...
   'ifft',    false,  ...
   'conf',    'dit',  ... 
   'order',   'nr',   ...
   'reorder', true,   ...
   'stages',  'r2r4', ...
   'dummy',   [] );

fftr4 = fft_c( fft_prm );

figure( ...
   'Name',        'FFT graph', ...
   'NumberTitle', 'off' );

ax = axes();

fftr4.graph( ax );
drawnow;
